apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: 5.0.8
    releaseName: minio
    namespace: minio
    includeCRDs: true
    valuesFile: values.yaml

generators:
  - ksops.yaml
