apiVersion: ENC[AES256_GCM,data:ErU=,iv:tE4nfemKni7+glFhu3DAlq54z0SIvE842h19qwBLknA=,tag:1DI9tslPAex5W+DZCj5r7Q==,type:str]
kind: ENC[AES256_GCM,data:eFDHwkSC,iv:RuJDnuinntrSeibeSDSjLXDsTskNLmiXnh70EnhAwUw=,tag:mvJotS6lZ8+YiQ26NmTwbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:czSwUxY=,iv:e++f2KcerP3Y/eom91lmkGTZ/G/Yhu6JgOiFC6zPX8o=,tag:DLw1NnvhBTyWxEJTVdp4Gw==,type:str]
type: ENC[AES256_GCM,data:eCN9YXYO,iv:c0P9LRkHtaHGoZ18lJMtKTSAdlQP32tWNitP6QuPXbo=,tag:7j65ZNNqrjZRktGgMX3z1w==,type:str]
stringData:
    rootUser: ENC[AES256_GCM,data:4CIQ2XLOuqg=,iv:e/d75CkYjeBm/JSK7zUgJ2vMl0IFwZHLkv0ZsEXZ4Rw=,tag:ALzo9h2XuSZZvtZqBErX8A==,type:str]
    rootPassword: ENC[AES256_GCM,data:JwkFLNIU89m4fdpG/D2zlA==,iv:TV+SnzBaf0oPUhmXqbbyZq2qgmEzLVHIiczPFjpx5Ro=,tag:mxwk11G5N0DXU+ldXcrzog==,type:str]
    lokiSecretKey: ENC[AES256_GCM,data:R8hW6rNMgXKVPn/Yq3RriA==,iv:ODkJQdgHhuTfHVdrVgW8ytnWXdEHDs17KTqP6hEuDok=,tag:dZtm/rGXHT2DHDW1XqEPng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1da7vm5p0m8xytkxswg5y9gk07n9fcs8cct0m5a2qthk7zh8dvfvspwwe0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdmUxa2YrRlZzV1RUKzg5
            bGFtWk5xN1QwWXErZ0l4NXJ4OE5SODkzd2w0ClBDUDU4S0RsYUIvMzRZeUpOVGs3
            ZCtYU1VRWXlaZmZOa0preXJPTnQ3UDAKLS0tIFNzRys2WmR6RDhabDZMTmtEc1hL
            RU5Yd085WnJWRTJjaDFyMzB6bXdDb3MKG1A2o9lZK6/ncp08VhlBYF0xDeBoYUzq
            Q/mBMOssOXR2tTJRh10IhqJeHNwZBT0i/rsAlT8OsMamZ6SxzsVXVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T05:57:56Z"
    mac: ENC[AES256_GCM,data:Ju9+SZh/Vm4UeEVGbFQqr/zVNWHziiFASCggRLS5nCEJzbrvpA+aTolW/qjcttwkSK8Mv75V2gaYJjJ9TzmNROOyFINRmS+bIkv2OdPdm0bwvtjOlGlqCwFy2fkaslmppMXlxBCT6dCZN2XG2PjoGiLbR+cq6owCcbaGQa9GIKc=,iv:PzLxsxZ1qsswKrmq56namUYSNF2Ud/XsZPo/A5TebKw=,tag:NI/n8agBov1eNuI81jXehQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
