existingSecret: minio
consoleIngress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - minio.chijun.website
  tls:
    - secretName: wilcard-chijun-website
      hosts:
        - "*.chijun.website"
policies:
  - name: loki
    statements:
      - resources:
          - "arn:aws:s3:::loki-*"
        actions:
          - "s3:*"
users:
  - accessKey: loki
    existingSecret: loki
    existingSecretKey: minioSecretKey
    policy: loki
persistence:
  size: 100Gi
replicas: 2
resources:
  requests:
    memory: 512Mi
