apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: longhorn
name: longhorn
repo: https://charts.longhorn.io
version: 1.4.0
releaseName: longhorn
namespace: longhorn-system
includeCRDs: true
valuesFile: values.yaml
