apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - namespace.yaml

generators:
  - helm.yaml

patchesStrategicMerge:
  - |-
    $patch: delete
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: longhorn-uninstall
      namespace: longhorn-system
  - |-
    $patch: delete
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: longhorn-post-upgrade
      namespace: longhorn-system
