persistence:
  defaultClassReplicaCount: 1
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
defaultSettings:
  defaultDataPath: /mnt/data
  defaultReplicaCount: 1
longhornUI:
  replicas: 1
longhornConversionWebhook:
  replicas: 1
longhornAdmissionWebhook:
  replicas: 1
longhornRecoveryBackend:
  replicas: 1
longhornDriver:
  replicas: 1
