defaultSettings:
  defaultDataPath: /mnt/data
  defaultReplicaCount: 1

preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornUI:
  replicas: 1

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.chijun.website
  tls: true
  tlsSecret: wildcard-chijun-website
