defaultSettings:
  defaultDataPath: /mnt/data
  defaultReplicaCount: 1

helmPreUpgradeCheckerJob:
  enabled: false

preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1


longhornUI:
  replicas: 1
