apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  labels:
    app.kubernetes.io/name: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
