apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
spec:
  ingressClassName: nginx
  rules:
    - host: "qbit.chijun.website"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: qbittorrent
                port:
                  number: 80
  tls:
    - hosts:
        - "*.chijun.website"
      secretName: wildcard-chijun-website
