apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

images:
  - name: "linuxserver/qbittorrent"
    newTag: "4.6.7"
