apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia

resources:
  - namespace.yaml
  - runtimeclass.yaml

helmCharts:
  - name: nvidia-device-plugin
    repo: https://nvidia.github.io/k8s-device-plugin
    version: 0.17.3
    releaseName: nvidia-device-plugin
    namespace: nvidia
    includeCRDs: true
    valuesFile: values.yaml

