apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argocd
name: argo-cd
repo: https://argoproj.github.io/argo-helm
version: 5.24.3
releaseName: argocd
namespace: argocd
includeCRDs: true
valuesFile: values.yaml
