fullnameOverride: argocd
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: false
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm
