fullnameOverride: argocd
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: false
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.1.1
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv $GOPATH/bin/kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-alpha-plugins --enable-helm --enable-exec
    accounts.argocd-bot: apiKey
  rbac:
    policy.csv: |
      g, argocd-bot, role:admin
