fullnameOverride: argocd
dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  enabled: true
repoServer:
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /ksops-age/keys.txt
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: ksops-age
      secret:
        secretName: ksops-age
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /ksops-age
      name: ksops-age
      readOnly: true
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.3
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-alpha-plugins --enable-helm --enable-exec
    accounts.argocd-bot: apiKey
  rbac:
    policy.csv: |
      g, argocd-bot, role:admin
