cloudflareAPIToken: ENC[AES256_GCM,data:QFkRqAQfmoQyBfq4Zuur55N9WfOqFdgyoOx8w8zFQ7HASXYV7SQagA==,iv:IGNrCty7hZgw88yiKeqeilpESXSK4NeItlKAR4Vrc8g=,tag:BpQRHGP4iIQPsEXX7xUIkQ==,type:str]
tailscaleAuthKey: ENC[AES256_GCM,data:lrUeE+BgJoK3MoGyLSRXCzPR0YGAyGFLJ+3iqqkaqFaDBEVE/CZwRD/vJ5m8EqCWtyur671iNqSm,iv:KXsNC2e/1qGwaRiKKgepYXznbazwC3oCbxE80dnZ3bQ=,tag:4lcCIAOXrtm3V/8ZBuuF5A==,type:str]
refreshInterval: ENC[AES256_GCM,data:OAF02g==,iv:iFyvVfi+dsVK/m9aE60WZ6sWvABQtidYb5/s5pWTo6g=,tag:XsuF0kpMKRhe9kHm9A34vw==,type:int]
mappings:
    - hostname: ENC[AES256_GCM,data:Sbx1PQq0yW0m5pl9pQ==,iv:jatVYlcc7p2ejoBlewspkPVKyzdwDDshq6BSgas1Src=,tag:9r0PRlLy0IFP9yHXvivURw==,type:str]
      records:
        - zone: ENC[AES256_GCM,data:odn6dTDt90eYoGwfVTM=,iv:hf0sXZ7OpPWXqL4SPZShro0I5WUk0l10ZQYyaid8VtQ=,tag:Pyz4KXk2Yq6dHLrvDqKJ7g==,type:str]
          names:
            - ENC[AES256_GCM,data:S/U4dPfGzjnvq1YiMbg=,iv:0SHA06qQei8pnL2mMRT+WhcI8JFVLHPKYBWiuqJDayY=,tag:Y27cGTMfSL9xSuAsdETXog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1da7vm5p0m8xytkxswg5y9gk07n9fcs8cct0m5a2qthk7zh8dvfvspwwe0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZWpLbHlwVi9EeEd3VEFE
            UGtCcSt1TkhpSklhQVkreVZ3SG9pM3YrbkZZCjFVelBlaUZDbnAzM0YzcGZVdjVT
            c1RBaW9SUWJZMVRrelloZUk4Z3FseW8KLS0tIHd4NG1pemlSN0lqajlyNFBhSG5D
            VUprcVoyMTlEejNNaXNtOHIrTXc5cW8Ks7QEry1SolFy0qEtoZtAuXJO8cfg7qaD
            TBdhFV/mxwjzLSGBp7XcaI1UPwVueVr1KpVAv/GUB++UL8cv7ADIcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T17:24:28Z"
    mac: ENC[AES256_GCM,data:pt12ACD2oSqnuBGsR/3Vo5WhJgfrnO0OtxdczaBQADpxoBgG2KBgX5EXxPzrrlGDRG8DAwIG/f/ql6J0STv5g3whboxkXlv4UK1BBvQk039LYdGMXmvDsMkPXsSXzthklbitxM2ks0CxJ4qvilGr5LlKU1FbyamZtV1pnnSrQZU=,iv:A9vyrV9lJqLAI8/4Kao/W6NphLoZj2bjR+kcMOMFJrA=,tag:n2Ytt3DP4c5JmsxrA5oatQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
