apiVersion: v1
kind: Secret
metadata:
    name: cfts-ddns
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:FlZBF2C39XJ8vewMPSDL0MPG64FqOTLkOJHnwZxOn8MIM0rUBdA6lD/02CbT83lwd4ZPUhs6Z8HfUHd7rkdgfFVsjLs8CZH6FC6JfMy2PgfSvDqX9yifkFBYskH49PydT5K60qu7KISylFXclg2kRFhaDmfxlzLuIFMhIPWMNujHPM9S4J30Q4+9GBJltj4M4T0M3T5LbsxO8jJcPkGX3KjvCPm85m58hbP3X3P7S0IwrXwdOc8+aVpW1laCx9xpunezpn6PbNZuYH0HtObKuerxcf0HR6EC+KZoy/U9D8m9+pAX7gzOJo7qqemRFVDW5S+CESKwkY7cWDIy972IKYKctXsPAaKa3I6KXZIYbhZcQwrFGkj7h6I7oH1gM0XLZlQgbNbdHK7kU/qy6MbrA6G3fepB3X1FsQvtnA3T,iv:MQ8Uio3f4bJkRBjFwkSI1ci+3407wCsSJDuktAm6sGw=,tag:MsZzFTcAkiKcqeXtvabIFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1da7vm5p0m8xytkxswg5y9gk07n9fcs8cct0m5a2qthk7zh8dvfvspwwe0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua1J0OUVHNTJiMEMwRlls
            SFNyd1EvNWxiTisxbXJnekdqRWRXMk9RWTJNCmg2MHpBcFptb2lXSDFzN1ArSWV5
            Y2pxNVI4L1cxenIwc093Wmc3eUdXOUUKLS0tIEJSM2w0SlVGQm1DZVo2Mzk1WklJ
            OGJ6K2Q2MXdQbm5ySUIwV2hvRTBRNjgK4gMrNhTTLLhOg2vhqqX8YigaNWkxZbTX
            HPbsg6R4AAhOn4PQkluSafRmHlrOcEHetOKTMTe2PkP3fovdjYotEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T18:33:02Z"
    mac: ENC[AES256_GCM,data:Z/sBHoY/PTHgNysnyZLOoXLx+oxqzpAu1XOEAaJa/m4FNImhVNytRBFh3rg2xc5DJ9X0UNzVxoM3qf88h+AtMX3WstnDCp5DC9ylFThWW7fVFgaG0V6T3105zvLW/r/3uemeoTByxoS+OrnM83im9jtf7z0cW6sYmEcHQ0Mvaq0=,iv:1n8QgKWz6TnuJ2PWHGWrjxFurIvb1M23lulJAjkNrNM=,tag:3yJyGkTGd+5q/4QngXXk9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
