apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.86.2
    releaseName: tailscale-operator
    namespace: ingress
    valuesFile: values.yaml

generators:
  - ksops.yaml
