apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.86.5
    releaseName: tailscale-operator
    namespace: ingress
    valuesFile: values.yaml

generators:
  - ksops.yaml

resources:
  - namespace.yaml
