- name: Check installed helm version
  ansible.builtin.command: helm version --short
  register: helm_installed
  changed_when: false
  failed_when: false

- name: Install helm
  when: helm_version not in helm_installed.stdout | default('')
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    extra_opts:
      - --strip-components=1
      - linux-amd64/helm
