apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      runtimeClassName: nvidia
      initContainers:
        - name: install-cjk-fonts
          image: debian:stable-slim
          command: ["/bin/sh", "-c"]
          args:
            - echo "installing fonts-noto-cjk...";
              apt update;
              apt install -y fonts-noto-cjk;
              echo "Done.";
          volumeMounts:
            - mountPath: /usr/share/fonts/opentype/noto
              name: noto
      containers:
        - name: jellyfin
          image: "linuxserver/jellyfin:10.8.10"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
          ports:
            - containerPort: 8096
              name: http
          volumeMounts:
            - mountPath: /data/media
              name: media-storage
            - mountPath: /config
              name: config
            - mountPath: /usr/share/fonts/opentype/noto
              name: noto
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-storage
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: noto
          emptyDir: {}
