apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      runtimeClassName: nvidia
      containers:
        - name: jellyfin
          image: "linuxserver/jellyfin:10.8.10"
          ports:
            - containerPort: 8096
              name: http
          volumeMounts:
            - mountPath: /data/media
              name: media-storage
            - mountPath: /config
              name: config
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-storage
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
