apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/name: httpbin-2
    includeSelectors: true

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: httpbin-2
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: httpbin-2
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: httpbin-2
      - op: replace
        path: /spec/rules/0/host
        value: "httpbin-2.chijun.website"

images:
  - name: "kennethreitz/httpbin"
    newTag: "latest"
