apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress

resources:
  - namespace.yaml
  - rbac.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.5.2
    releaseName: ingress-nginx
    namespace: ingress
    includeCRDs: true
    valuesFile: values.yaml

generators:
  - ksops.yaml
