apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
name: grafana
repo: https://grafana.github.io/helm-charts
version: 6.55.0
releaseName: grafana
namespace: monitoring
valuesFile: values.yaml
