apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.3.2
    releaseName: grafana
    namespace: monitoring
    valuesFile: values.yaml

generators:
  - ksops.yaml
