apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - configmap.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: 2025.9.1
