apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki
repo: https://grafana.github.io/helm-charts
version: 5.2.0
releaseName: loki
namespace: monitoring
valuesFile: values.yaml
