apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.2.0
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml

generators:
  - ksops.yaml
