loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: "s3"
    s3:
      endpoint: "http://minio.minio:9000"
      accessKeyId: "loki"
      secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
      s3ForcePathStyle: true
      insecure: true
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"
singleBinary:
  replicas: 1
  extraArgs:
    - "-config.expand-env"
  extraEnv:
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki
          key: minioSecretKey
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
test:
  enabled: false
