apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: homelab
    metrics: 0.0.0.0:2000
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    ingress:
    - hostname: "*.chijun.website"
      service: http://ingress-nginx-controller.ingress:80
    - service: http_status:404
