apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
            - name: mqtt
              containerPort: 1883
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: configmap
              subPath: mosquitto.conf
      volumes:
        - name: configmap
          configMap:
            name: mosquitto
