apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: eclipse-mosquitto
    newTag: 2.0.22
