apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
  annotations:
    tailscale.com/tags: tag:homelab-k3s-mosquitto
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
  selector:
    app.kubernetes.io/name: mosquitto
