apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 27.32.0
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml
