apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: promtail
name: promtail
repo: https://grafana.github.io/helm-charts
version: 6.11.0
releaseName: promtail
namespace: monitoring
