apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.0
    releaseName: promtail
    namespace: monitoring
