apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - pvc.yaml
  - deployment.yaml
  - rbac.yaml

generators:
  - ksops.yaml

images:
  - name: "ghcr.io/tailscale/tailscale"
    newTag: "v1.86.5"
