sources:
  - ingress

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

extraArgs:
  cloudflare-record-comment: "provisioned by external-dns"

excludeDomains:
  - "*.chijun.website"
