apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: firefly-iii
name: firefly-iii
repo: https://firefly-iii.github.io/kubernetes
version: 1.4.0
releaseName: firefly-iii
namespace: default
valuesInline:
  config:
    existingSecret: "firefly-iii"
    env:
      TZ: "Asia/Kuala_Lumpur"
      DB_CONNECTION: sqlite
      DB_DATABASE: ""
      DB_PORT: ""
      DB_USERNAME: ""
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - money.chijun.website
    tls:
      - secretName: wildcard-chijun-website
        hosts:
          - "*.chijun.website"
