apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - pvc.yaml

helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes
    version: 1.9.11
    releaseName: firefly-iii
    namespace: default
    valuesFile: values.yaml

generators:
  - ksops.yaml

patches:
  - target:
      kind: Deployment
      name: firefly-iii
    patch: |-
      - op: replace
        path: /kind
        value: StatefulSet
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value: 
          mountPath: /var/www/html/storage/database
          name: database
      - op: add
        path: /spec/template/spec/volumes/-
        value: 
          name: database
          persistentVolumeClaim:
            claimName: firefly-iii-database
