apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-state-metrics
name: kube-state-metrics
repo: https://prometheus-community.github.io/helm-charts
version: 5.0.0
releaseName: kube-state-metrics
namespace: kube-system
includeCRDs: true
