apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - rbac.yaml
  - service.yaml

generators:
  - ksops.yaml

images:
  - name: "syncthing:syncthing"
    newTag: "1.23.4"
  - name: "ghcr.io/tailscale/tailscale:v1.40.0"
    newTag: "v1.40.0"
