apiVersion: ENC[AES256_GCM,data:dtc=,iv:1/YmJf8397ybl+L0prT80xWU3rK9LV+tBsenxfdxeP0=,tag:/cvqGJdCEt8xUwy2p+CSyQ==,type:str]
kind: ENC[AES256_GCM,data:8H/ovr4h,iv:jN+RhrGtsvrYimixvqtXNJ/u2YftgHl9sXfBHyMjgoE=,tag:34qHI10vOqDjihH+Hleamg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HkhJ0HSab6ux,iv:L8QFdd2BziqsjTkJccrlZsxmztJW2eIMPP9Y1UISJ+o=,tag:Q21HPxyeL0Vj4l15KO5jew==,type:str]
type: ENC[AES256_GCM,data:Ti+Y4Ngq,iv:37/gx8WrhK26WOz5xCWvWJLX4lEnMoPgWfP4JQvy/CA=,tag:XPds8ucaWg0t9Jku7TY6LA==,type:str]
stringData:
    tailscaleAuthKey: ENC[AES256_GCM,data:6t7C53IovWCLxbC7OdRv6eoqsGnY9GgwqvwKKNXzs8J90iO1NRsbBiCwofTjOJweCkeE+//THusj,iv:x/tYZ085U4B/lXBpY6QsH/rSGfnZV8U8iqzIHbM4FP8=,tag:JQP5YXSagTq4hZDVbu1L4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1da7vm5p0m8xytkxswg5y9gk07n9fcs8cct0m5a2qthk7zh8dvfvspwwe0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM3JrWHpRb3UzNXo2QzRp
            UEk3SzVua28xayt1eVYxYWVjT0E0dlRBV3pvCnRLc3NTNkViN254OFNjdlJZWTIz
            Q1RBUnBkZmpWNTFZVGpYWDZENEtBWEkKLS0tIFM4YzVFV0c3bFAwY2N3UmkxaGMw
            T1JBSFN3cEV5MGFtQVN0dExvY2lYNEkKYTH7MNh7uHXPw/riACtQyoNU3CdXkR8c
            rdj9ANHJkKG16f9z0/mIx3YuyXxC4Fl1vpFMFtOCnQ2/UtypzcWMyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T13:15:30Z"
    mac: ENC[AES256_GCM,data:v6kskLgfoPQUQg316BTYoaGF8TQ/stAmAuT/31ZK8xXvm7WMUCZmmFJ2DDda6o41HG6erY7vflEvV3Mh6wSUaDO9kvdY3gSB6G5M5Ew4HcbpciuhaO0pV+pMaKpJY/sENKWEbYImQL5XgS7B4ro8EAdYzRP/NwuQOFAETyQDIak=,iv:EKPRTnhtGoCTQQVhwVqB0XAN/7X8tnajs01i0kM9MYM=,tag:4SXJx4pT1Wu+SRcv0USGrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
