apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
secretFrom:
  - metadata:
      name: argocd-bot
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    type: Opaque
    files:
      - config.yaml=config.enc.yaml
      - key.pem=key.enc.pem
