apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true
