apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: metrics-server
name: metrics-server
repo: https://kubernetes-sigs.github.io/metrics-server/
version: 3.8.3
releaseName: metrics-server
namespace: kube-system
includeCRDs: true
