apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterissuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.11.0
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesInline:
      installCRDs: true

generators:
  - ksops.yaml
